### ISSUE TITLE
Error api.class.php on line 32

### ISSUE THREAD

**Issue by geison66** [pronebird/wp-clanwars#1]
Hi @pronebird ,
I have the follow error when i active the plugin.

**Fatal error:** Can't use function return value in write context in **../wp-content/plugins/wp-clanwars/classes/api.class.php** on line **32**

How i can solve this?

**Comment by pronebird** [comment]
Hi @geison66,

`master` is not yet ready for production so there may be issues.

Please use the latest release available at:

https://github.com/pronebird/wp-clanwars/releases

_or_

http://wordpress.org/plugins/wp-clanwars

**Comment by geison66** [comment]
Hi @pronebird,
Do you have any estimate of when the `master` will be ready?
Because the plugin is fantastic, but I really need the function to show both teams.

Congratulations for the plugin and thanks for the response.

**Comment by pronebird** [comment]
@geison66 Not exactly sure as I don't have much free time recently. I may spend some time prepping v2.0 in the second half of February.

**Comment by xeedyad** [comment]
Hi @pronebird ,
I have the follow error when i active the plugin.

Parse error: syntax error, unexpected '*', expecting ',' or ';' in .......wp-clanwars-master/wp-clanwars-widget.php on line 31
