### ISSUE TITLE
NEED A UPDATE

### ISSUE THREAD

**Issue by Veneno101** [pronebird/wp-clanwars#2]
wordpress cant handle the plugin. 

if someone has a working version plizz help me :D

**Comment by pronebird** [comment]
Hi,

What version of WordPress do you use?

**Comment by Veneno101** [comment]
Hey again!

the problem is the pluging cant make new games, like it says.
as you see here, then i click "Get started" it get to a erorr, it only says, my website cant handle the request?


Den 25. marts 2017 kl. 15.14.51 +01.00, skrev Andrei Mihailov <notifications@github.com>:

**Comment by Veneno101** [comment]
and what zip file is it, there is needed to upload a game?


Den 28. marts 2017 kl. 08.31.00 +02.00, skrev veneno@solidarityesport.com:

**Comment by pronebird** [comment]
I just installed fresh WP 4.7 and wp-clanwars through Plugins -> Add New in wp-admin. Everything seems to be working as before. Maybe try re-activating the plug-in. Not sure why you experience this.

ZIP files are used to export created games so you could share them. Currently plug-in comes with a few pre-created games but I am working on making it possible to share created games via cloud.

**Comment by pronebird** [comment]
Hi, is this related to #3 ?
