### ISSUE TITLE
Issue when activating plugin

### ISSUE THREAD

**Issue by itsmemac** [pronebird/wp-clanwars#4]
Installed your plugin and then this happened
![capture2](https://user-images.githubusercontent.com/37410297/45025043-0a3a3e80-b058-11e8-91ea-e301bbd82da6.JPG)

earlier i installed directly from wordpress plugin directory and i got same error message but with wp-clanwars-widget.php in line 329
so edited and removed "}" in the line 329 and  its gave me the same issue as above.
So downloaded from git and this happened.
Help me fix it.

**Comment by pronebird** [comment]
Hi,

Are you sure you don't have WP-Clanwars installed twice?

**Comment by itsmemac** [comment]
oh, my theme Game Addict comes with pre installed clan wars
But it doesn't seems to work

**Comment by pronebird** [comment]
Yep, they bundle their own modified copy of WP-Clanwars with their theme. I am afraid that I am not affiliated with Game Addict and I suggest you to reach out to the seller for support. 😕

**Comment by itsmemac** [comment]
thank you for the support
